from collections.abc import Mapping
from typing import Any, Optional

class AlignmentStructure:
    def __getitem__(self, key: str) -> Any: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def optimal_alignment_score(self) -> int: ...
    @property
    def suboptimal_alignment_score(self) -> int: ...
    @property
    def target_begin(self) -> int: ...
    @property
    def target_end_optimal(self) -> int: ...
    @property
    def target_end_suboptimal(self) -> int: ...
    @property
    def query_begin(self) -> int: ...
    @property
    def query_end(self) -> int: ...
    @property
    def cigar(self) -> str: ...
    @property
    def query_sequence(self) -> str: ...
    @property
    def target_sequence(self) -> str: ...
    @property
    def aligned_query_sequence(self) -> Optional[str]: ...
    @property
    def aligned_target_sequence(self) -> Optional[str]: ...
    def set_zero_based(self, is_zero_based: bool) -> None: ...
    def is_zero_based(self) -> bool: ...

class StripedSmithWaterman:
    def __init__(self, query_sequence: str, **kwargs: Any) -> None:
        """Keyword args include gap_open_penalty, gap_extend_penalty, score_size,
        mask_length, mask_auto, score_only, score_filter, distance_filter,
        override_skip_babp, protein, match_score, mismatch_score,
        substitution_matrix, suppress_sequences, and zero_index.
        """

    def __call__(self, target_sequence: str) -> AlignmentStructure: ...
